version: '3.7'
services:
  gerocuidado-usuario-api:
    image: node:18.13.0
    container_name: gerocuidado-usuario-api
    volumes:
      - .:/home/node/app
    entrypoint: bash /home/node/app/.docker/entrypoint.sh
    environment:
      - NODE_ENV=development
    ports:
      - '3001:3001'
      - '4001:4001'
      - '7001:9001'
    depends_on:
      - gerocuidado-usuario-db
    networks:
      - gerocuidado-usuario-net
      - gerocuidado-apis-net

  gerocuidado-usuario-db:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - './db/postgres:/var/lib/postgresql/data'
      - './.docker/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_DB=gerocuidado-usuario-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5001:5001'
    networks:
      - gerocuidado-usuario-net

networks:
  gerocuidado-usuario-net:
    driver: bridge
  gerocuidado-apis-net:
    name: gerocuidado-apis-net
    external: true
